"""
Indian PET Plastic Credit Framework
Flask Backend — app.py (Supabase/PostgreSQL version)
"""

from flask import Flask, render_template, request, jsonify, session, redirect, url_for, send_file
from werkzeug.security import generate_password_hash, check_password_hash
import os, random, string, io
from datetime import datetime, timedelta
from functools import wraps
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import psycopg2
import psycopg2.extras
from dotenv import load_dotenv
load_dotenv()

app = Flask(__name__)
app.secret_key = os.environ.get('SECRET_KEY', 'pet-credit-iitdelhi-2026-xK9m2pQnv8')

# --- Geospatial classifier (lat/lon -> collection category, F, E, evidence) ---
# Loaded lazily on first use — takes ~1s to read, done once per worker process.
# These are small, pre-simplified/pre-reprojected parquet files (committed to
# git, ~40MB total) generated by preprocess_geo_data.py from the original
# ~200MB raw government datasets. Render's 512MB Starter instance was getting
# OOM-killed reading the raw files directly (just deserializing the 150MB
# rivers file alone cost ~1.3GB of RAM) — see the memory notes at the top of
# GeoClassifier.__init__ in geo_classifier.py for the full story. Because the
# small files are committed to git, there's nothing to download at deploy
# time anymore; if one is missing, that's a real problem (bad clone/commit),
# not a normal first-run state, so this fails loudly instead of trying to
# fetch and reprocess the raw ~200MB datasets on a memory-constrained instance.
_geo_classifier = None
def get_classifier():
    global _geo_classifier
    if _geo_classifier is None:
        base_dir = os.path.dirname(os.path.abspath(__file__))
        rivers_path = os.path.join(base_dir, "Rivers+ Streams", "wris_rivers_simplified.parquet")
        if not os.path.exists(rivers_path):
            raise FileNotFoundError(
                "Missing Rivers+ Streams/wris_rivers_simplified.parquet (and likely the other "
                "4 pre-processed geo files). These must be committed to git — run "
                "`python preprocess_geo_data.py` locally (with the raw datasets present) and "
                "commit the *_simplified.parquet / esz_reprojected.parquet outputs."
            )
        from geo_classifier import GeoClassifier
        _geo_classifier = GeoClassifier(verbose=False)
    return _geo_classifier

# Rough India bounding box — reject obviously-wrong coordinates before hitting the classifier
INDIA_BBOX = {'lat_min': 6.0, 'lat_max': 38.0, 'lon_min': 68.0, 'lon_max': 98.0}

import urllib.parse

def get_db():
    url = os.environ.get('DATABASE_URL', '')
    result = urllib.parse.urlparse(url)
    return psycopg2.connect(
        host=result.hostname,
        port=result.port or 6543,
        database=result.path[1:],
        user=result.username,
        password=urllib.parse.unquote(result.password or ''),
        sslmode='require'
    )

def fetchone(cursor):
    row = cursor.fetchone()
    if row is None:
        return None
    return {cursor.description[i][0]: row[i] for i in range(len(row))}

def fetchall(cursor):
    rows = cursor.fetchall()
    return [{cursor.description[i][0]: row[i] for i in range(len(row))} for row in rows]

def init_db():
    conn = get_db()
    c = conn.cursor()
    # Superadmin seed
    c.execute("SELECT id FROM companies WHERE email='gandhijidaksh@gmail.com'")
    existing = fetchone(c)
    if not existing:
        c.execute('''INSERT INTO companies (company_name, email, password, is_verified, is_admin)
                     VALUES (%s, %s, %s, 1, 1)''',
                  ('IIT Delhi Admin', 'gandhijidaksh@gmail.com',
                   generate_password_hash('admin123')))
    else:
        c.execute("UPDATE companies SET is_admin=1 WHERE email='gandhijidaksh@gmail.com'")

    # Create company_profiles table
    c.execute("""
        CREATE TABLE IF NOT EXISTS company_profiles (
            company_id   INTEGER PRIMARY KEY,
            contact_name TEXT DEFAULT '',
            mobile       TEXT DEFAULT '',
            address      TEXT DEFAULT '',
            gstin        TEXT DEFAULT '',
            updated_at   TIMESTAMP DEFAULT NOW()
        )
    """)

    # Create company_documents table
    c.execute("""
        CREATE TABLE IF NOT EXISTS company_documents (
            id           SERIAL PRIMARY KEY,
            company_id   INTEGER NOT NULL,
            doc_type     TEXT NOT NULL,
            filename     TEXT NOT NULL,
            file_size_kb INTEGER DEFAULT 0,
            file_data    BYTEA,
            uploaded_at  TIMESTAMP DEFAULT NOW(),
            UNIQUE(company_id, doc_type)
        )
    """)

    conn.commit()
    conn.close()

def get_setting(key):
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT value FROM settings WHERE key=%s', (key,))
    row = fetchone(c)
    conn.close()
    return row['value'] if row else ''

def send_email(to_email, subject, html_body):
    smtp_email    = os.environ.get('SMTP_EMAIL') or get_setting('smtp_email')
    smtp_password = os.environ.get('SMTP_PASSWORD') or get_setting('smtp_password')
    smtp_host     = os.environ.get('SMTP_HOST') or get_setting('smtp_host')
    smtp_port     = int(os.environ.get('SMTP_PORT') or get_setting('smtp_port') or 587)
    if not smtp_password:
        print(f'[EMAIL] No SMTP password set. Would send to {to_email}: {subject}')
        return False
    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        from email.utils import formataddr
        msg['From'] = formataddr(('IIT Delhi PET Credit Portal', smtp_email))
        msg['To']   = to_email
        msg.attach(MIMEText(html_body, 'html'))
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_email, smtp_password)
            server.sendmail(smtp_email, to_email, msg.as_string())
        return True
    except Exception as e:
        print(f'[EMAIL ERROR] {e}')
        return False

def generate_otp(length=6):
    return ''.join(random.choices(string.digits, k=length))

def create_otp(email, purpose):
    otp = generate_otp()
    expires_at = datetime.now() + timedelta(minutes=10)
    conn = get_db()
    c = conn.cursor()
    c.execute('UPDATE otp_store SET used=1 WHERE email=%s AND purpose=%s', (email, purpose))
    c.execute('INSERT INTO otp_store (email, otp, purpose, expires_at) VALUES (%s,%s,%s,%s)',
              (email, otp, purpose, expires_at))
    conn.commit()
    conn.close()
    return otp

def verify_otp(email, otp, purpose):
    conn = get_db()
    c = conn.cursor()
    c.execute('''SELECT * FROM otp_store
        WHERE email=%s AND otp=%s AND purpose=%s AND used=0
        AND expires_at > NOW()
        ORDER BY id DESC LIMIT 1''', (email, otp, purpose))
    row = fetchone(c)
    if row:
        c.execute('UPDATE otp_store SET used=1 WHERE id=%s', (row['id'],))
        conn.commit()
    conn.close()
    return row is not None

def login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if 'company_id' not in session:
            return redirect(url_for('login_page'))
        return f(*args, **kwargs)
    return decorated

def admin_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get('is_admin'):
            return redirect(url_for('login_page'))
        return f(*args, **kwargs)
    return decorated

def log_action(company_id, company_name, email, action):
    try:
        conn = get_db()
        c = conn.cursor()
        c.execute('''INSERT INTO access_log (company_id, company_name, email, action, ip_address)
                     VALUES (%s, %s, %s, %s, %s)''',
                  (company_id, company_name, email, action, request.remote_addr or 'unknown'))
        conn.commit()
        conn.close()
    except Exception as e:
        print(f'[LOG ERROR] {e}')

# ============================================================
# PAGE ROUTES
# ============================================================
@app.route('/')
def index():
    if 'company_id' in session:
        if session.get('is_admin'):
            return redirect(url_for('admin_dashboard'))
        return redirect(url_for('dashboard'))
    return redirect(url_for('login_page'))

@app.route('/login')
def login_page():
    if 'company_id' in session:
        return redirect(url_for('index'))
    return render_template('login.html')

@app.route('/dashboard')
@login_required
def dashboard():
    if session.get('is_admin'):
        return redirect(url_for('admin_dashboard'))
    return render_template('dashboard.html',
                           company_name=session.get('company_name'),
                           email=session.get('email'))

@app.route('/admin')
@admin_required
def admin_dashboard():
    return render_template('admin.html')

# ============================================================
# AUTH ROUTES
# ============================================================
@app.route('/api/register', methods=['POST'])
def register():
    data         = request.get_json()
    company_name = data.get('company_name', '').strip()
    email        = data.get('email', '').strip().lower()
    password     = data.get('password', '')
    if not company_name or not email or not password:
        return jsonify({'ok': False, 'error': 'All fields are required.'})
    if len(password) < 6:
        return jsonify({'ok': False, 'error': 'Password must be at least 6 characters.'})
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT id FROM companies WHERE email=%s', (email,))
    if fetchone(c):
        conn.close()
        return jsonify({'ok': False, 'error': 'An account with this email already exists.'})
    c.execute('INSERT INTO companies (company_name, email, password, is_verified) VALUES (%s,%s,%s,0)',
              (company_name, email, generate_password_hash(password)))
    conn.commit()
    conn.close()
    otp = create_otp(email, 'verify')
    print(f'[VERIFY OTP for {email}]: {otp}')
    send_email(email, 'Verify your PET Credit Portal account',
        f'''<div style="font-family:sans-serif;max-width:480px;margin:auto;padding:32px;background:#0d1117;color:#e6edf3;border-radius:12px;">
        <h2 style="color:#1a9e8f;">♻️ PET Plastic Credit Portal</h2>
        <p style="margin-top:16px;">Your verification OTP is:</p>
        <div style="font-size:36px;font-weight:bold;letter-spacing:10px;color:#1a9e8f;margin:20px 0;">{otp}</div>
        <p style="color:#8b949e;font-size:13px;">This OTP expires in 10 minutes. Do not share it.</p>
        </div>''')
    return jsonify({'ok': True, 'step': 'verify', 'email': email})

@app.route('/api/verify-registration', methods=['POST'])
def verify_registration():
    data  = request.get_json()
    email = data.get('email', '').strip().lower()
    otp   = data.get('otp', '').strip()
    if not verify_otp(email, otp, 'verify'):
        return jsonify({'ok': False, 'error': 'Invalid or expired OTP. Please try again.'})
    conn = get_db()
    c = conn.cursor()
    c.execute('UPDATE companies SET is_verified=1 WHERE email=%s', (email,))
    conn.commit()
    c.execute('SELECT * FROM companies WHERE email=%s', (email,))
    company = fetchone(c)
    conn.close()
    session['company_id']   = company['id']
    session['company_name'] = company['company_name']
    session['email']        = email
    session['is_admin']     = bool(company['is_admin'])
    log_action(company['id'], company['company_name'], email, 'registered')
    return jsonify({'ok': True, 'redirect': url_for('dashboard')})

@app.route('/api/login', methods=['POST'])
def login():
    data     = request.get_json()
    email    = data.get('email', '').strip().lower()
    password = data.get('password', '')
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT * FROM companies WHERE email=%s', (email,))
    company = fetchone(c)
    conn.close()
    if not company or not check_password_hash(company['password'], password):
        return jsonify({'ok': False, 'error': 'Invalid email or password.'})
    if company['is_admin']:
        session['company_id']   = company['id']
        session['company_name'] = company['company_name']
        session['email']        = email
        session['is_admin']     = True
        log_action(company['id'], company['company_name'], email, 'logged_in')
        return jsonify({'ok': True, 'redirect': url_for('admin_dashboard')})
    otp  = create_otp(email, 'login')
    sent = send_email(email, 'Your PET Credit Portal login OTP',
        f'''<div style="font-family:sans-serif;max-width:480px;margin:auto;padding:32px;background:#0d1117;color:#e6edf3;border-radius:12px;">
        <h2 style="color:#1a9e8f;">♻️ PET Plastic Credit Portal</h2>
        <p style="margin-top:16px;">Your login OTP is:</p>
        <div style="font-size:36px;font-weight:bold;letter-spacing:10px;color:#1a9e8f;margin:20px 0;">{otp}</div>
        <p style="color:#8b949e;font-size:13px;">This OTP expires in 10 minutes.</p>
        </div>''')
    if not sent:
        print(f'[LOGIN OTP for {email}]: {otp}')
    return jsonify({'ok': True, 'step': 'otp', 'email': email})

@app.route('/api/verify-login-otp', methods=['POST'])
def verify_login_otp():
    data  = request.get_json()
    email = data.get('email', '').strip().lower()
    otp   = data.get('otp', '').strip()
    if not verify_otp(email, otp, 'login'):
        return jsonify({'ok': False, 'error': 'Invalid or expired OTP. Please try again.'})
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT * FROM companies WHERE email=%s', (email,))
    company = fetchone(c)
    conn.close()
    if not company:
        return jsonify({'ok': False, 'error': 'Account not found.'})
    session['company_id']   = company['id']
    session['company_name'] = company['company_name']
    session['email']        = email
    session['is_admin']     = bool(company['is_admin'])
    log_action(company['id'], company['company_name'], email, 'logged_in')
    redirect_url = url_for('admin_dashboard') if company['is_admin'] else url_for('dashboard')
    return jsonify({'ok': True, 'redirect': redirect_url})

@app.route('/api/forgot-password', methods=['POST'])
def forgot_password():
    data  = request.get_json()
    email = data.get('email', '').strip().lower()
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT * FROM companies WHERE email=%s', (email,))
    company = fetchone(c)
    conn.close()
    if company:
        otp = create_otp(email, 'reset')
        print(f'[RESET OTP for {email}]: {otp}')
        send_email(email, 'Reset your PET Credit Portal password',
            f'''<div style="font-family:sans-serif;max-width:480px;margin:auto;padding:32px;background:#0d1117;color:#e6edf3;border-radius:12px;">
            <h2 style="color:#1a9e8f;">♻️ PET Plastic Credit Portal</h2>
            <p style="margin-top:16px;">Your password reset OTP is:</p>
            <div style="font-size:36px;font-weight:bold;letter-spacing:10px;color:#1a9e8f;margin:20px 0;">{otp}</div>
            <p style="color:#8b949e;font-size:13px;">This OTP expires in 10 minutes.</p>
            </div>''')
    return jsonify({'ok': True, 'message': f'If {email} is registered, a reset OTP has been sent.'})

@app.route('/api/reset-password', methods=['POST'])
def reset_password():
    data         = request.get_json()
    email        = data.get('email', '').strip().lower()
    otp          = data.get('otp', '').strip()
    new_password = data.get('new_password', '')
    if len(new_password) < 6:
        return jsonify({'ok': False, 'error': 'Password must be at least 6 characters.'})
    if not verify_otp(email, otp, 'reset'):
        return jsonify({'ok': False, 'error': 'Invalid or expired OTP.'})
    conn = get_db()
    c = conn.cursor()
    c.execute('UPDATE companies SET password=%s WHERE email=%s',
              (generate_password_hash(new_password), email))
    conn.commit()
    conn.close()
    log_action(None, None, email, 'password_reset')
    return jsonify({'ok': True, 'message': 'Password reset successfully. Please log in.'})

@app.route('/api/logout', methods=['POST'])
def logout():
    if 'company_id' in session:
        log_action(session['company_id'], session.get('company_name'),
                   session.get('email'), 'logged_out')
    session.clear()
    return jsonify({'ok': True, 'redirect': url_for('login_page')})

# ============================================================
# PCC ENTRIES
# ============================================================
@app.route('/api/pcc', methods=['GET'])
@login_required
def get_pcc():
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT * FROM pcc_entries WHERE company_id=%s ORDER BY month_idx, id',
              (session['company_id'],))
    rows = fetchall(c)
    conn.close()
    return jsonify(rows)

@app.route('/api/pcc', methods=['POST'])
@login_required
def add_pcc():
    d = request.get_json()
    conn = get_db()
    c = conn.cursor()
    record_date = datetime.now().strftime('%d %B %Y')
    c.execute('''INSERT INTO pcc_entries
        (company_id, month_idx, date_str, record_date, category, weight, esg, loc_f, eco_e, esg_g, pcc,
         lat, lon, verified, evidence, confidence)
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING id''',
        (session['company_id'], d['month_idx'], d['date_str'], record_date, d['category'],
         d['weight'], d['esg'], d['loc_f'], d['eco_e'], d['esg_g'], d['pcc'],
         d.get('lat'), d.get('lon'), bool(d.get('verified', False)), d.get('evidence'), d.get('confidence')))
    new_id = c.fetchone()[0]
    conn.commit()
    conn.close()
    return jsonify({'ok': True, 'id': new_id})

@app.route('/api/pcc/<int:entry_id>', methods=['PUT'])
@login_required
def update_pcc(entry_id):
    d = request.get_json()
    conn = get_db()
    c = conn.cursor()
    c.execute('''UPDATE pcc_entries SET
        date_str=%s, category=%s, weight=%s, esg=%s, loc_f=%s, eco_e=%s, esg_g=%s, pcc=%s,
        lat=%s, lon=%s, verified=%s, evidence=%s, confidence=%s
        WHERE id=%s AND company_id=%s''',
        (d['date_str'], d['category'], d['weight'], d['esg'],
         d['loc_f'], d['eco_e'], d['esg_g'], d['pcc'],
         d.get('lat'), d.get('lon'), bool(d.get('verified', False)), d.get('evidence'), d.get('confidence'),
         entry_id, session['company_id']))
    conn.commit()
    conn.close()
    return jsonify({'ok': True})

@app.route('/api/classify-location', methods=['POST'])
@login_required
def classify_location():
    d = request.get_json(silent=True) or {}
    try:
        lat = float(d['lat'])
        lon = float(d['lon'])
    except (KeyError, TypeError, ValueError):
        return jsonify({'error': 'lat and lon are required numeric fields'}), 400

    if not (INDIA_BBOX['lat_min'] <= lat <= INDIA_BBOX['lat_max'] and
            INDIA_BBOX['lon_min'] <= lon <= INDIA_BBOX['lon_max']):
        return jsonify({'error': 'coordinates fall outside India — check lat/lon order and values'}), 400

    try:
        result = get_classifier().classify(lat, lon)
    except Exception as e:
        return jsonify({'error': f'classification failed: {e}'}), 500

    return jsonify(result)

@app.route('/api/pcc/bulk-classify', methods=['POST'])
@login_required
def bulk_classify_location():
    d = request.get_json(silent=True) or {}
    points = d.get('points')
    if not isinstance(points, list) or not points:
        return jsonify({'error': 'points array required'}), 400
    if len(points) > 500:
        return jsonify({'error': 'max 500 points per batch'}), 400

    clf = get_classifier()
    results = []
    for p in points:
        try:
            lat = float(p.get('lat'))
            lon = float(p.get('lon'))
        except (TypeError, ValueError):
            results.append({'error': 'invalid lat/lon'})
            continue
        if not (INDIA_BBOX['lat_min'] <= lat <= INDIA_BBOX['lat_max'] and
                INDIA_BBOX['lon_min'] <= lon <= INDIA_BBOX['lon_max']):
            results.append({'error': 'coordinates outside India'})
            continue
        try:
            results.append(clf.classify(lat, lon))
        except Exception as e:
            results.append({'error': f'classification failed: {e}'})
    return jsonify({'results': results})

@app.route('/api/pcc/<int:entry_id>', methods=['DELETE'])
@login_required
def delete_pcc(entry_id):
    conn = get_db()
    c = conn.cursor()
    c.execute('DELETE FROM pcc_entries WHERE id=%s AND company_id=%s',
              (entry_id, session['company_id']))
    conn.commit()
    conn.close()
    return jsonify({'ok': True})

# ============================================================
# PPC ENTRIES
# ============================================================
@app.route('/api/ppc', methods=['GET'])
@login_required
def get_ppc():
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT * FROM ppc_entries WHERE company_id=%s ORDER BY month_idx, id',
              (session['company_id'],))
    rows = fetchall(c)
    conn.close()
    return jsonify(rows)

@app.route('/api/ppc', methods=['POST'])
@login_required
def add_ppc():
    d = request.get_json()
    conn = get_db()
    c = conn.cursor()
    record_date = datetime.now().strftime('%d %B %Y')
    c.execute('''INSERT INTO ppc_entries
        (company_id, month_idx, date_str, record_date, product, weight, esg,
         service_life, exposure_p, proc_w, esg_g, ppc, weight_gross, weight_wasted)
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING id''',
        (session['company_id'], d['month_idx'], d['date_str'], record_date, d['product'],
         d['weight'], d['esg'], d['service_life'], d['exposure_p'],
         d['proc_w'], d['esg_g'], d['ppc'], d.get('weight_gross'), d.get('weight_wasted')))
    new_id = c.fetchone()[0]
    conn.commit()
    conn.close()
    return jsonify({'ok': True, 'id': new_id})

@app.route('/api/ppc/<int:entry_id>', methods=['PUT'])
@login_required
def update_ppc(entry_id):
    d = request.get_json()
    conn = get_db()
    c = conn.cursor()
    c.execute('''UPDATE ppc_entries SET
        date_str=%s, product=%s, weight=%s, esg=%s,
        service_life=%s, exposure_p=%s, proc_w=%s, esg_g=%s, ppc=%s,
        weight_gross=%s, weight_wasted=%s
        WHERE id=%s AND company_id=%s''',
        (d['date_str'], d['product'], d['weight'], d['esg'],
         d['service_life'], d['exposure_p'], d['proc_w'], d['esg_g'], d['ppc'],
         d.get('weight_gross'), d.get('weight_wasted'),
         entry_id, session['company_id']))
    conn.commit()
    conn.close()
    return jsonify({'ok': True})

@app.route('/api/ppc/<int:entry_id>', methods=['DELETE'])
@login_required
def delete_ppc(entry_id):
    conn = get_db()
    c = conn.cursor()
    c.execute('DELETE FROM ppc_entries WHERE id=%s AND company_id=%s',
              (entry_id, session['company_id']))
    conn.commit()
    conn.close()
    return jsonify({'ok': True})

# ============================================================
# COMPANY PROFILE (company-side)
# ============================================================
@app.route('/api/profile', methods=['GET'])
@login_required
def get_profile():
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT * FROM company_profiles WHERE company_id=%s', (session['company_id'],))
    row = fetchone(c)
    conn.close()
    if not row:
        return jsonify({'contact_name':'','mobile':'','address':'','gstin':''})
    return jsonify(row)

@app.route('/api/profile', methods=['POST'])
@login_required
def save_profile():
    d = request.get_json()
    conn = get_db()
    c = conn.cursor()
    c.execute("""
        INSERT INTO company_profiles (company_id, contact_name, mobile, address, gstin, updated_at)
        VALUES (%s,%s,%s,%s,%s,NOW())
        ON CONFLICT (company_id) DO UPDATE SET
            contact_name = EXCLUDED.contact_name,
            mobile       = EXCLUDED.mobile,
            address      = EXCLUDED.address,
            gstin        = EXCLUDED.gstin,
            updated_at   = NOW()
    """, (session['company_id'], d.get('contact',''), d.get('mobile',''),
          d.get('address',''), d.get('gstin','')))
    conn.commit()
    conn.close()
    return jsonify({'ok': True})

# ============================================================
# COMPANY DOCUMENTS (company-side)
# ============================================================
@app.route('/api/document/<doc_type>', methods=['GET'])
@login_required
def get_document_meta(doc_type):
    if doc_type not in ('esg', 'plastic', 'extra'):
        return jsonify({'exists': False}), 400
    conn = get_db()
    c = conn.cursor()
    c.execute("""SELECT doc_type, filename, file_size_kb, uploaded_at
                 FROM company_documents WHERE company_id=%s AND doc_type=%s""",
              (session['company_id'], doc_type))
    row = fetchone(c)
    conn.close()
    if not row:
        return jsonify({'exists': False})
    if row.get('uploaded_at'):
        row['uploaded_at'] = str(row['uploaded_at'])
    row['exists'] = True
    return jsonify(row)

@app.route('/api/document/<doc_type>', methods=['POST'])
@login_required
def upload_document(doc_type):
    if doc_type not in ('esg', 'plastic', 'extra'):
        return jsonify({'ok': False, 'error': 'Invalid document type'}), 400
    if 'file' not in request.files:
        return jsonify({'ok': False, 'error': 'No file provided'}), 400
    f = request.files['file']
    if not f.filename:
        return jsonify({'ok': False, 'error': 'Empty filename'}), 400
    file_bytes = f.read()
    if len(file_bytes) > 10 * 1024 * 1024:
        return jsonify({'ok': False, 'error': 'File exceeds 10 MB limit'}), 400
    conn = get_db()
    c = conn.cursor()
    c.execute("""
        INSERT INTO company_documents (company_id, doc_type, filename, file_size_kb, file_data, uploaded_at)
        VALUES (%s,%s,%s,%s,%s,NOW())
        ON CONFLICT (company_id, doc_type) DO UPDATE SET
            filename     = EXCLUDED.filename,
            file_size_kb = EXCLUDED.file_size_kb,
            file_data    = EXCLUDED.file_data,
            uploaded_at  = NOW()
    """, (session['company_id'], doc_type, f.filename,
          len(file_bytes) // 1024, psycopg2.Binary(file_bytes)))
    conn.commit()
    conn.close()
    return jsonify({'ok': True, 'filename': f.filename, 'size_kb': len(file_bytes) // 1024})

@app.route('/api/document/<doc_type>/download', methods=['GET'])
@login_required
def download_own_document(doc_type):
    """Company downloads their own document."""
    if doc_type not in ('esg', 'plastic', 'extra'):
        return jsonify({'error': 'Invalid doc type'}), 400
    conn = get_db()
    c = conn.cursor()
    c.execute("SELECT filename, file_data FROM company_documents WHERE company_id=%s AND doc_type=%s",
              (session['company_id'], doc_type))
    row = fetchone(c)
    conn.close()
    if not row or not row['file_data']:
        return jsonify({'error': 'Not found'}), 404
    return send_file(io.BytesIO(bytes(row['file_data'])),
                     download_name=row['filename'], as_attachment=True)

@app.route('/api/document/<doc_type>', methods=['DELETE'])
@login_required
def delete_document(doc_type):
    if doc_type not in ('esg', 'plastic', 'extra'):
        return jsonify({'ok': False}), 400
    conn = get_db()
    c = conn.cursor()
    c.execute("DELETE FROM company_documents WHERE company_id=%s AND doc_type=%s",
              (session['company_id'], doc_type))
    conn.commit()
    conn.close()
    return jsonify({'ok': True})

# ============================================================
# ADMIN — COMPANIES
# ============================================================
@app.route('/api/admin/companies', methods=['GET'])
@admin_required
def admin_companies():
    conn = get_db()
    c = conn.cursor()
    c.execute('''
        SELECT c.id, c.company_name, c.email, c.created_at, c.is_verified, c.is_admin,
               COUNT(DISTINCT p.id) as pcc_count,
               COUNT(DISTINCT q.id) as ppc_count,
               COALESCE(SUM(p.pcc),0) as total_pcc,
               COALESCE(SUM(q.ppc),0) as total_ppc,
               -- CO2 is tracked on PPC (processing) entries only, in tonnes CO2 per tonne PET
               -- (t/t). Not on PCC: the report has no collection-stage CO2 figure, and since the
               -- same material typically earns a PCC credit on collection then a PPC credit when
               -- later processed (see the report's own worked example), adding a PCC-side CO2
               -- estimate on top of the PPC-side one would double-count the same avoided-emissions
               -- event -- once as a guess, once for real. See CO2_RATES comment below.
               (SELECT COALESCE(SUM(weight * CASE product
                 WHEN %s THEN 1.7  WHEN %s THEN 1.8  WHEN %s THEN 1.8
                 WHEN %s THEN 0.43 WHEN %s THEN 0.43 WHEN %s THEN 0.43
                 -- Road construction: report gives 3.5 t CO2/km of road, not a per-tonne-of-plastic
                 -- rate -- not convertible without assuming road width/bitumen content, so it is
                 -- excluded from the CO2 total (0) rather than mis-credited at another product's rate.
                 WHEN %s THEN 0.43 WHEN %s THEN 0.25 WHEN %s THEN 0
                 ELSE 0.43 END),0) FROM ppc_entries WHERE company_id=c.id) as total_co2
        FROM companies c
        LEFT JOIN pcc_entries p ON p.company_id = c.id
        LEFT JOIN ppc_entries q ON q.company_id = c.id
        WHERE c.is_admin = 0
        GROUP BY c.id
        ORDER BY c.created_at DESC
    ''', ('Bottle-to-bottle PET','Reusable shopping bag','Polyester apparel',
          'Blanket / Comforter','Carpet / Rug','Geotextile',
          'Plastic crate','WPC panel','Road construction'))
    companies = fetchall(c)
    conn.close()
    for co in companies:
        if co.get('created_at'):
            co['created_at'] = str(co['created_at'])
    return jsonify(companies)

@app.route('/api/admin/companies/<int:company_id>', methods=['PUT'])
@admin_required
def admin_update_company(company_id):
    d = request.get_json()
    conn = get_db()
    c = conn.cursor()
    c.execute('UPDATE companies SET company_name=%s, email=%s WHERE id=%s',
              (d['company_name'], d['email'], company_id))
    conn.commit()
    conn.close()
    return jsonify({'ok': True})

@app.route('/api/admin/companies/<int:company_id>', methods=['DELETE'])
@admin_required
def admin_delete_company(company_id):
    conn = get_db()
    c = conn.cursor()
    c.execute('DELETE FROM pcc_entries WHERE company_id=%s', (company_id,))
    c.execute('DELETE FROM ppc_entries WHERE company_id=%s', (company_id,))
    c.execute('DELETE FROM company_documents WHERE company_id=%s', (company_id,))
    c.execute('DELETE FROM company_profiles WHERE company_id=%s', (company_id,))
    c.execute('DELETE FROM companies WHERE id=%s', (company_id,))
    conn.commit()
    conn.close()
    log_action(None, 'Admin', session.get('email'), f'deleted_company_{company_id}')
    return jsonify({'ok': True})

@app.route('/api/admin/companies/<int:company_id>/reset-password', methods=['POST'])
@admin_required
def admin_reset_password(company_id):
    d = request.get_json()
    new_password = d.get('password', '')
    if len(new_password) < 6:
        return jsonify({'ok': False, 'error': 'Password must be at least 6 characters.'})
    conn = get_db()
    c = conn.cursor()
    c.execute('UPDATE companies SET password=%s WHERE id=%s',
              (generate_password_hash(new_password), company_id))
    conn.commit()
    conn.close()
    return jsonify({'ok': True})

# ============================================================
# ADMIN — LOGS
# ============================================================
@app.route('/api/admin/logs', methods=['GET'])
@admin_required
def admin_logs():
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT * FROM access_log ORDER BY timestamp DESC LIMIT 200')
    logs = fetchall(c)
    conn.close()
    for log in logs:
        if log.get('timestamp'):
            log['timestamp'] = str(log['timestamp'])
    return jsonify(logs)

@app.route('/api/admin/logs', methods=['DELETE'])
@admin_required
def admin_clear_logs():
    conn = get_db()
    c = conn.cursor()
    c.execute('DELETE FROM access_log')
    conn.commit()
    conn.close()
    return jsonify({'ok': True})

# ============================================================
# ADMIN — SUMMARY
# ============================================================
@app.route('/api/admin/summary', methods=['GET'])
@admin_required
def admin_summary():
    conn = get_db()
    c = conn.cursor()
    c.execute("SELECT COUNT(*) as n FROM companies WHERE is_admin=0")
    total_companies = fetchone(c)['n']
    c.execute('SELECT COALESCE(SUM(pcc),0) as s FROM pcc_entries')
    total_pcc = fetchone(c)['s']
    c.execute('SELECT COALESCE(SUM(ppc),0) as s FROM ppc_entries')
    total_ppc = fetchone(c)['s']
    c.execute("SELECT COUNT(*) as n FROM access_log WHERE action='logged_in'")
    total_logins = fetchone(c)['n']
    conn.close()
    return jsonify({
        'total_companies': total_companies,
        'total_pcc':       round(float(total_pcc), 4),
        'total_ppc':       round(float(total_ppc), 4),
        'total_logins':    total_logins
    })

# ============================================================
# ADMIN — REPORT
# ============================================================
@app.route('/api/admin/report/<int:company_id>/json', methods=['GET'])
@admin_required
def admin_company_report(company_id):
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT * FROM companies WHERE id=%s', (company_id,))
    company = fetchone(c)
    if not company:
        conn.close()
        return jsonify({'error': 'Company not found'}), 404
    c.execute('SELECT * FROM pcc_entries WHERE company_id=%s ORDER BY month_idx, id', (company_id,))
    pcc_list = fetchall(c)
    c.execute('SELECT * FROM ppc_entries WHERE company_id=%s ORDER BY month_idx, id', (company_id,))
    ppc_list = fetchall(c)
    conn.close()
    MONTHS = ['January','February','March','April','May','June',
              'July','August','September','October','November','December']
    # Rates are tonnes CO2 saved per tonne of PET (t/t -- same numeric value as the report's own
    # kg-per-kg ratios, just relabeled to keep every CO2 figure in this app in one consistent
    # unit). Taken from the IIT Delhi report's climate co-benefits section (ALPLA 2017, TecRecyc,
    # Greiner 2024, NPC India, Zhang et al. 2020):
    #   - Bottle-to-bottle PET (1.7), Reusable shopping bag / Polyester apparel (1.8),
    #     WPC panel (0.25) are the report's directly-stated figures.
    #   - Blanket/Comforter, Carpet/Rug, Geotextile, Plastic crate (0.43) use the report's own
    #     fallback method -- "product-level carbon footprint values provide a basis for
    #     estimating emission benefits [when] direct CO2 savings are not explicitly reported"
    #     -- applying the r-PET flakes carbon footprint (0.43 t/t, Greiner 2024) as a proxy.
    #   - Road construction is set to 0 (excluded), NOT 0.25: the report reports this pathway as
    #     3.5 t CO2 saved per km of road built, a different unit that can't be converted to a
    #     per-tonne-of-plastic rate without assuming road width/bitumen content, so crediting it
    #     at another product's rate would misrepresent the report.
    CO2_RATES = {'Bottle-to-bottle PET':1.7,'Reusable shopping bag':1.8,
                 'Polyester apparel':1.8,'Blanket / Comforter':0.43,'Carpet / Rug':0.43,
                 'Geotextile':0.43,'Plastic crate':0.43,'WPC panel':0.25,'Road construction':0}
    # CO2 is tracked on PPC (processing) entries only -- not PCC. The report has no collection-
    # stage CO2 figure, and since the same material typically earns a PCC credit on collection
    # then a PPC credit when later processed, adding a PCC-side CO2 estimate on top of the PPC-
    # side one would double-count the same avoided-emissions event. total_co2 is in tonnes CO2
    # (weight is already tonnes of PET).
    total_co2 = sum(r['weight'] * CO2_RATES.get(r['product'], 0.43) for r in ppc_list)
    company = dict(company)
    if company.get('created_at'):
        company['created_at'] = str(company['created_at'])
    return jsonify({'company': company, 'pcc': pcc_list, 'ppc': ppc_list,
                    'months': MONTHS, 'total_co2': round(total_co2, 2)})

# ============================================================
# ADMIN — COMPANY PROFILES (read-only view)
# ============================================================
@app.route('/api/admin/profiles', methods=['GET'])
@admin_required
def admin_all_profiles():
    """List all companies with profile completion + doc count for the profiles tab."""
    conn = get_db()
    c = conn.cursor()
    c.execute("""
        SELECT c.id, c.company_name, c.email, c.created_at, c.is_verified,
               p.contact_name, p.mobile, p.address, p.gstin,
               p.updated_at as profile_updated,
               (SELECT COUNT(*) FROM company_documents d WHERE d.company_id=c.id) as doc_count,
               (SELECT COALESCE(SUM(pe.pcc),0) FROM pcc_entries pe WHERE pe.company_id=c.id) as total_pcc,
               (SELECT COALESCE(SUM(pp.ppc),0) FROM ppc_entries pp WHERE pp.company_id=c.id) as total_ppc,
               (SELECT COUNT(*) FROM pcc_entries WHERE company_id=c.id) as pcc_count,
               (SELECT COUNT(*) FROM ppc_entries WHERE company_id=c.id) as ppc_count,
               -- CO2 is tracked on PPC entries only, not PCC -- see CO2_RATES comment in
               -- admin_company_report() for why (avoids double-counting the same material's
               -- avoided emissions at both collection and processing). Rates in t CO2/t PET.
               (SELECT COALESCE(SUM(weight * CASE product
                 WHEN 'Bottle-to-bottle PET' THEN 1.7  WHEN 'Reusable shopping bag' THEN 1.8
                 WHEN 'Polyester apparel' THEN 1.8     WHEN 'Blanket / Comforter' THEN 0.43
                 WHEN 'Carpet / Rug' THEN 0.43         WHEN 'Geotextile' THEN 0.43
                 WHEN 'Plastic crate' THEN 0.43        WHEN 'WPC panel' THEN 0.25
                 WHEN 'Road construction' THEN 0       ELSE 0.43 END),0)
               FROM ppc_entries WHERE company_id=c.id) as total_co2
        FROM companies c
        LEFT JOIN company_profiles p ON p.company_id = c.id
        WHERE c.is_admin = 0
        ORDER BY c.company_name
    """)
    rows = fetchall(c)
    conn.close()
    for r in rows:
        if r.get('created_at'):    r['created_at']    = str(r['created_at'])
        if r.get('profile_updated'): r['profile_updated'] = str(r['profile_updated'])
        r['doc_count'] = int(r.get('doc_count') or 0)
    return jsonify(rows)

@app.route('/api/admin/profile/<int:company_id>', methods=['GET'])
@admin_required
def admin_get_company_profile(company_id):
    """Full profile + documents for one company (accordion detail view)."""
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT * FROM companies WHERE id=%s', (company_id,))
    company = fetchone(c)
    if not company:
        conn.close()
        return jsonify({'error': 'Not found'}), 404
    c.execute('SELECT * FROM company_profiles WHERE company_id=%s', (company_id,))
    profile = fetchone(c)
    c.execute("""SELECT doc_type, filename, file_size_kb, uploaded_at
                 FROM company_documents WHERE company_id=%s ORDER BY doc_type""", (company_id,))
    docs = fetchall(c)
    conn.close()
    for d in docs:
        if d.get('uploaded_at'):
            d['uploaded_at'] = str(d['uploaded_at'])
    company = dict(company)
    if company.get('created_at'):
        company['created_at'] = str(company['created_at'])
    if company.get('password'):
        del company['password']   # never send password hash
    return jsonify({'company': company, 'profile': profile or {}, 'documents': docs})

@app.route('/api/admin/document/<int:company_id>/<doc_type>/download', methods=['GET'])
@admin_required
def admin_download_document(company_id, doc_type):
    """Admin downloads any company's document."""
    if doc_type not in ('esg', 'plastic', 'extra'):
        return jsonify({'error': 'Invalid doc type'}), 400
    conn = get_db()
    c = conn.cursor()
    c.execute("SELECT filename, file_data FROM company_documents WHERE company_id=%s AND doc_type=%s",
              (company_id, doc_type))
    row = fetchone(c)
    conn.close()
    if not row or not row['file_data']:
        return jsonify({'error': 'Not found'}), 404
    return send_file(io.BytesIO(bytes(row['file_data'])),
                     download_name=row['filename'], as_attachment=True)

# ============================================================
# ADMIN — ADMINS
# ============================================================
@app.route('/api/admin/create-admin', methods=['POST'])
@admin_required
def create_admin():
    d = request.get_json()
    name     = d.get('name', '').strip()
    email    = d.get('email', '').strip().lower()
    password = d.get('password', '')
    if not name or not email or not password:
        return jsonify({'ok': False, 'error': 'All fields are required.'})
    if len(password) < 6:
        return jsonify({'ok': False, 'error': 'Password must be at least 6 characters.'})
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT id FROM companies WHERE email=%s', (email,))
    if fetchone(c):
        conn.close()
        return jsonify({'ok': False, 'error': 'An account with this email already exists.'})
    c.execute('INSERT INTO companies (company_name, email, password, is_verified, is_admin) VALUES (%s,%s,%s,1,1)',
              (name, email, generate_password_hash(password)))
    conn.commit()
    conn.close()
    log_action(None, 'Admin', session.get('email'), f'created_admin_{email}')
    return jsonify({'ok': True})

@app.route('/api/admin/admins/<int:admin_id>', methods=['DELETE'])
@admin_required
def delete_admin(admin_id):
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT email FROM companies WHERE id=%s', (admin_id,))
    admin = fetchone(c)
    if admin and admin['email'] == 'gandhijidaksh@gmail.com':
        conn.close()
        return jsonify({'ok': False, 'error': 'Cannot delete the superadmin account.'})
    c.execute('DELETE FROM companies WHERE id=%s AND is_admin=1', (admin_id,))
    conn.commit()
    conn.close()
    return jsonify({'ok': True})

@app.route('/api/admin/admins', methods=['GET'])
@admin_required
def list_admins():
    conn = get_db()
    c = conn.cursor()
    c.execute("SELECT id, company_name, email, created_at FROM companies WHERE is_admin=1 ORDER BY created_at")
    admins = fetchall(c)
    conn.close()
    for a in admins:
        if a.get('created_at'):
            a['created_at'] = str(a['created_at'])
    return jsonify(admins)

# ============================================================
# ADMIN — SETTINGS
# ============================================================
@app.route('/api/admin/settings', methods=['GET'])
@admin_required
def admin_get_settings():
    conn = get_db()
    c = conn.cursor()
    c.execute('SELECT key, value FROM settings')
    rows = fetchall(c)
    conn.close()
    settings = {r['key']: r['value'] for r in rows}
    settings['smtp_password'] = '••••••••' if settings.get('smtp_password') else ''
    return jsonify(settings)

@app.route('/api/admin/settings', methods=['POST'])
@admin_required
def admin_update_settings():
    d = request.get_json()
    conn = get_db()
    c = conn.cursor()
    for key in ['smtp_email', 'smtp_host', 'smtp_port']:
        if key in d:
            c.execute('INSERT INTO settings (key,value) VALUES (%s,%s) ON CONFLICT (key) DO UPDATE SET value=%s',
                      (key, d[key], d[key]))
    if d.get('smtp_password') and d['smtp_password'] != '••••••••':
        c.execute('INSERT INTO settings (key,value) VALUES (%s,%s) ON CONFLICT (key) DO UPDATE SET value=%s',
                  ('smtp_password', d['smtp_password'], d['smtp_password']))
    conn.commit()
    conn.close()
    return jsonify({'ok': True})

@app.route('/api/admin/test-email', methods=['POST'])
@admin_required
def admin_test_email():
    sent = send_email('gandhijidaksh@gmail.com',
                      'PET Credit Portal — Email Test',
                      '<h2>✅ Email is working correctly.</h2>')
    return jsonify({'ok': sent, 'message': 'Test email sent!' if sent else 'Failed — check SMTP settings.'})

# ============================================================
# ENTRY POINT
# ============================================================
if __name__ == '__main__':
    init_db()
    print("\n✅ PET Plastic Credit Portal running at http://127.0.0.1:5000")
    print("   Admin login: gandhijidaksh@gmail.com / admin123\n")
    port = int(os.environ.get('PORT', 5000))
    app.run(debug=False, host='0.0.0.0', port=port)